spring:
  application:
    name: 'spring-cloud-kafka-dlq'
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customerdb
      username: customerdb
      password: customerdb
  cloud:
    function:
      definition: productCreatedConsume
    stream:
      kafka:
        binder:
          brokers: 'localhost:9092'
          auto-create-topics: true
          auto-add-partitions: true
          consumer-properties:
            max.poll.records: 20
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
          dlq-producer-properties:
            configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
            configuration.value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer
        bindings:
          productCreatedConsume-in-0:
            consumer:
              auto-commit-offset: true
              auto-commit-on-error: false
              ack-each-record: true
              configuration:
                max.poll.interval.ms: 10000
      bindings:
        productCreatedConsume-in-0:
          destination: 'queueing.example.product.created'
          group: ${spring.application.name}-product-created
          content-type: application/json
          consumer:
            max-attempts: 10
            default-retryable: true

logging:
  level:
    org.springframework: INFO
    net.elau.example.springmongoreactive: DEBUG